spring:
  application:
    name: test
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/testdb
    user: postgres
    password: postgres
    baseline-on-migrate: true