/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("org.springframework.boot:spring-boot-starter-web:3.2.4")

}

dependencyLocking {
    lockMode = LockMode.STRICT
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
